### PR TITLE
RUA-25760

### PR DESCRIPTION
**Pull request by llasapg**
https://rabota.atlassian.net/browse/RUA-25760

yaml update

### CODE REVIEW

**Review by marchenko1985 — APPROVED** [review]

**Comment by svcrua** [comment]
**docker** - failure

https://github.com/rabotaua/actions-common-docker/actions/runs/6221321811

**Comment by svcrua** [comment]
**docker** - failure

https://github.com/rabotaua/actions-common-docker/actions/runs/6221322311

**Comment by svcrua** [comment]
**docker** - failure

https://github.com/rabotaua/actions-common-docker/actions/runs/6222799396

**Comment by svcrua** [comment]
**docker** - failure

https://github.com/rabotaua/actions-common-docker/actions/runs/6222798926

**Comment by svcrua** [comment]
**docker** - failure

https://github.com/rabotaua/actions-common-docker/actions/runs/6223324539

**Pull request merged**
